# Copyright (c) 2025, Midas and contributors
# License: MIT. See LICENSE
"""Atomic bid opening execution (PROC-STORY-054)."""

from __future__ import annotations

import hashlib
from typing import Any

import frappe
from frappe import _
from frappe.utils import now_datetime

from kentender_procurement.services.opening_candidate_bids import resolve_candidate_bids_for_tender
from kentender_procurement.services.opening_post_opening import lock_opening_register_and_finalize
from kentender_procurement.services.opening_preconditions import validate_opening_preconditions

BS = "Bid Submission"
BOR = "Bid Opening Register"
BOS = "Bid Opening Session"
BOEL = "Bid Opening Event Log"


def _norm(s: str | None) -> str:
	return (s or "").strip()


def _event_hash(payload: str) -> str:
	return "sha256:" + hashlib.sha256(payload.encode("utf-8")).hexdigest()


def execute_bid_opening(session_id: str, *, actor_user: str | None = None) -> dict[str, Any]:
	"""Run precondition checks, resolve candidates, generate register + lines, open bids, log events.

	Finishes by locking the register and marking the session (PROC-STORY-055 hook).
	"""
	sid = _norm(session_id)
	if not sid:
		frappe.throw(_("Opening session is required."), frappe.ValidationError)

	if not frappe.db.exists(BOS, sid):
		frappe.throw(_("Bid Opening Session not found."), frappe.ValidationError)

	tender_id = _norm(frappe.db.get_value(BOS, sid, "tender"))
	if not tender_id:
		frappe.throw(_("Session has no tender."), frappe.ValidationError)

	pc = validate_opening_preconditions(tender_id, sid)
	if not pc.get("ok"):
		detail = next((c.get("detail") for c in pc.get("checks") or [] if not c.get("ok")), _("Preconditions failed."))
		frappe.throw(_("{0}").format(detail), frappe.ValidationError, title=_("Opening blocked"))

	res = resolve_candidate_bids_for_tender(tender_id)
	candidates = res.get("candidates") or []
	excluded = res.get("excluded") or []

	actor = _norm(actor_user) or frappe.session.user
	now = now_datetime()

	biz = f"BOR-{frappe.generate_hash(length=12)}"

	reg = frappe.get_doc(
		{
			"doctype": BOR,
			"business_id": biz,
			"tender": tender_id,
			"bid_opening_session": sid,
			"status": "Generated",
			"generated_on": now,
			"generated_by_user": actor,
			"opening_datetime": now,
			"total_submitted_bids": len(candidates) + len(excluded),
			"total_opened_bids": len(candidates),
			"total_excluded_bids": len(excluded),
			"summary_notes": _("Auto-generated by opening execution."),
			"register_lines": [],
		}
	)

	for c in candidates:
		bname = c.get("name")
		row = frappe.db.get_value(
			BS,
			bname,
			["supplier", "submitted_on", "receipt_no", "quoted_total_amount", "currency"],
			as_dict=True,
		)
		reg.append(
			"register_lines",
			{
				"bid_submission": bname,
				"supplier": (row or {}).get("supplier") or c.get("supplier"),
				"submission_timestamp": (row or {}).get("submitted_on"),
				"receipt_no": (row or {}).get("receipt_no") or "",
				"was_opened": 1,
				"was_excluded": 0,
				"quoted_total_amount": (row or {}).get("quoted_total_amount"),
				"currency": (row or {}).get("currency"),
			},
		)

	for e in excluded:
		bname = e.get("bid_submission")
		if not bname:
			continue
		row = frappe.db.get_value(
			BS,
			bname,
			["supplier", "submitted_on", "receipt_no", "quoted_total_amount", "currency"],
			as_dict=True,
		)
		reg.append(
			"register_lines",
			{
				"bid_submission": bname,
				"supplier": (row or {}).get("supplier") or "",
				"submission_timestamp": (row or {}).get("submitted_on"),
				"receipt_no": (row or {}).get("receipt_no") or "",
				"was_opened": 0,
				"was_excluded": 1,
				"exclusion_reason": ", ".join(e.get("reasons") or []),
				"quoted_total_amount": (row or {}).get("quoted_total_amount"),
				"currency": (row or {}).get("currency"),
			},
		)

	reg.insert(ignore_permissions=True)

	for c in candidates:
		bname = c.get("name")
		frappe.db.set_value(
			BS,
			bname,
			{
				"workflow_state": "Opened",
				"status": "Opened",
				"sealed_status": "Opened",
				"is_opening_visible": 1,
				"opened_on": now,
				"opened_by_session": sid,
			},
			update_modified=False,
		)

	frappe.get_doc(
		{
			"doctype": BOEL,
			"bid_opening_session": sid,
			"event_type": "Register Generated",
			"event_datetime": now,
			"actor_user": actor,
			"event_summary": _("Opening register {0} generated.").format(reg.name),
			"result_status": "Success",
			"event_hash": _event_hash(f"register|{reg.name}|{sid}"),
		}
	).insert(ignore_permissions=True)

	frappe.db.set_value(
		BOS,
		sid,
		{
			"workflow_state": "Completed",
			"status": "Completed",
			"actual_opening_datetime": now,
			"session_closed_datetime": now,
			"opened_bid_count": len(candidates),
			"excluded_bid_count": len(excluded),
			"is_atomic_opening_complete": 1,
			"register_generated": 1,
			"opening_register": reg.name,
			"precondition_check_status": "Pass",
			"opening_triggered_by": actor,
		},
		update_modified=False,
	)

	lock_opening_register_and_finalize(reg.name, sid, actor_user=actor)

	return {
		"session": sid,
		"tender": tender_id,
		"register": reg.name,
		"opened_count": len(candidates),
		"excluded_count": len(excluded),
		"candidates": [c.get("name") for c in candidates],
	}
